### ISSUE TITLE
Removing password message after successful (or unsuccessful) login attempt

### ISSUE THREAD

**Issue by Abadulrehman** [leam-tech/frappe_telegram#3]
It would be better to automatically delete the message in which the user types out a password (perhaps as soon as the bot receives it and can store it) so that it doesn't just stay in their chat history as a ticking-security-time-bomb. 💣 😅 `python-telegram-bot` does support deleting messages.

**Comment by fahimalizain** [comment]
@Abadulrehman please check the latest behavior and let us know what you think

**Comment by Abadulrehman** [comment]
Auto-deletes/replaces the password now. :+1:  Issue successfully resolved.
